// <auto-generated />
using Elite.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elite.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250319115055_initWithProductsAndCategory")]
    partial class initWithProductsAndCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elite.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayOrder = 1,
                            Name = "Phone Cases & Covers"
                        },
                        new
                        {
                            ID = 2,
                            DisplayOrder = 2,
                            Name = "Screen Protectors"
                        },
                        new
                        {
                            ID = 3,
                            DisplayOrder = 3,
                            Name = "Chargers & Cables"
                        },
                        new
                        {
                            ID = 4,
                            DisplayOrder = 4,
                            Name = "Audio Accessories"
                        },
                        new
                        {
                            ID = 5,
                            DisplayOrder = 5,
                            Name = "Bluetooth Speakers"
                        },
                        new
                        {
                            ID = 6,
                            DisplayOrder = 6,
                            Name = "Lens protection"
                        },
                        new
                        {
                            ID = 7,
                            DisplayOrder = 7,
                            Name = "Power Banks"
                        });
                });

            modelBuilder.Entity("Elite.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "GRABIST",
                            Description = "A magnatic case for samsung galaxy s24 ultra, full camera protection with lens, black",
                            Price = 200.0,
                            Price100 = 150.0,
                            Price50 = 170.0,
                            ProductName = "S24 Ultra Case"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Gtech",
                            Description = "A magnatic transparent case for iphone 15 pro max case, combatible with magnatic charger",
                            Price = 155.0,
                            Price100 = 130.0,
                            Price50 = 140.0,
                            ProductName = "Iphone 15 pro max case"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dalaa mobilak",
                            Description = "A flexible silicon case for Oppo Find X 5 Case, grey",
                            Price = 175.0,
                            Price100 = 140.0,
                            Price50 = 150.0,
                            ProductName = "Oppo Find X 5 Case"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "JOYROOM",
                            Description = "high quality screen protector, transparent",
                            Price = 500.0,
                            Price100 = 430.0,
                            Price50 = 450.0,
                            ProductName = "Iphone 13 pro max screen protector"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Anker",
                            Description = "high quality screen protector, transparent",
                            Price = 500.0,
                            Price100 = 430.0,
                            Price50 = 450.0,
                            ProductName = "Iphone 14 pro max screen protector"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Generic",
                            Description = "high quality screen protector, transparent",
                            Price = 400.0,
                            Price100 = 350.0,
                            Price50 = 370.0,
                            ProductName = "S24 Ultra screen protector"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Anker",
                            Description = "20W USB-C Power Supply Charging",
                            Price = 600.0,
                            Price100 = 550.0,
                            Price50 = 570.0,
                            ProductName = "Anker Power Port 3 Charger"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Xiaomi",
                            Description = "33W USB-C Power Supply Charging",
                            Price = 200.0,
                            Price100 = 150.0,
                            Price50 = 170.0,
                            ProductName = "Xiaomi Charger"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "JOYROOM",
                            Description = "a Joyroom 3 in 1 wireless charger for apple products",
                            Price = 1200.0,
                            Price100 = 1150.0,
                            Price50 = 1170.0,
                            ProductName = "Joyroom wireless charger"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Apple",
                            Description = "A wirless charger from apple.",
                            Price = 2200.0,
                            Price100 = 2150.0,
                            Price50 = 2170.0,
                            ProductName = "Mag Safe Charger"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "JBL",
                            Description = "black wired hand-free from jbl",
                            Price = 250.0,
                            Price100 = 190.0,
                            Price50 = 210.0,
                            ProductName = "JBL Tune 110 Earphone"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "GRABIST",
                            Description = "bluetooth 5.3, powerful bass, itelligent touch control",
                            Price = 3200.0,
                            Price100 = 3150.0,
                            Price50 = 3170.0,
                            ProductName = "Xiaomi Redmi Buds 4 active"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Apple",
                            Description = "Premium apple Airpods with noise cancelation",
                            Price = 9800.0,
                            Price100 = 9150.0,
                            Price50 = 9570.0,
                            ProductName = "Apple AirPods 3"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Anker",
                            Description = "Bluetooth speaker with ipx7 waterproof protection, 20W ,12h playtime, black",
                            Price = 2000.0,
                            Price100 = 1500.0,
                            Price50 = 1750.0,
                            ProductName = "Soundcore Flare 2"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "JBL",
                            Description = "ip67 waterproof speaker w bold JBL original pro sound, 12h battery, 1 year warranty",
                            Price = 5600.0,
                            Price100 = 5100.0,
                            Price50 = 5200.0,
                            ProductName = "JBL Flib 6 Portal"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "JBL",
                            Description = "ip67 waterproof 7h playtime, playtimeboost and JBL Pro Sound",
                            Price = 3200.0,
                            Price100 = 3150.0,
                            Price50 = 3170.0,
                            ProductName = "JBL Go 4 Portable"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "GRABIST",
                            Description = "tempered glass and ultra-thin aluminum",
                            Price = 90.0,
                            Price100 = 50.0,
                            Price50 = 70.0,
                            ProductName = "S24 Ultra lens"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "GRABIST",
                            Description = "tempered glass and ultra-thin aluminum",
                            Price = 200.0,
                            Price100 = 150.0,
                            Price50 = 170.0,
                            ProductName = "Iphone 16 lens"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Reioo",
                            Description = "Reioo 9H tempered glass and ultra-thin aluminum",
                            Price = 70.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            ProductName = "samsung A54 lens"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Anker",
                            Description = "10.000mAh portable charger and PD 30W",
                            Price = 300.0,
                            Price100 = 250.0,
                            Price50 = 270.0,
                            ProductName = "Anker Nano Power Bank"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Xiaomi",
                            Description = "10.000mAh portable charger and 6-moth warranty",
                            Price = 200.0,
                            Price100 = 150.0,
                            Price50 = 170.0,
                            ProductName = "Xiaomi Redmi Power Bank"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
